import {PETS,PET_ITEMS,petSnapshot,petStage,dailyReadingStars} from './pets-model.js';
import {today} from './core.js';
export const petPicture=(id,stage=0,extra='')=>`<img class="pet-picture ${extra}" src="./pets/${id}-${stage}.png" alt="${PETS.find(p=>p.id===id).stages[stage]}" loading="lazy">`;
function stageView(pet,stage,p){return `<div class="pet-stage" data-pet-stage data-pet="${pet.id}" data-stage="${stage}" data-scene="${p.equipped.scene}" data-rug="${p.equipped.rug}" data-bowl="${p.equipped.bowl}" role="img" aria-label="${pet.stages[stage]}，立体小伙伴，可左右拖动看看">${petPicture(pet.id,stage)}</div>`;}
export function petHome(state){
  const p=petSnapshot(state),owned=p.owned.find(x=>x.id===p.selected),pet=PETS.find(x=>x.id===(p.selected||'bunny')),stage=petStage(owned?.feeds.length||0),next=stage===0?3:9;
  return `<section class="pet-home scene-${p.equipped.scene}"><div class="pet-top"><span>${owned?'我的阅读小伙伴':'有个小伙伴，在等你'}</span><button class="star-wallet" data-action="pet-rules" aria-label="星星规则，现有${p.balance}颗星星">✦ ${p.balance}</button></div>${stageView(pet,stage,p)}<div class="pet-greeting"><h2>${owned?pet.name+'，'+pet.stages[stage]:'把第一位小伙伴接回家'}</h2><p id="pet-message" aria-live="polite">${owned?'读过的故事，会变成陪伴它的星星。':'小兔、小猫、小狗、小猴，还有小凤凰。'}</p></div>${owned?`<div class="pet-growth"><span>${stage===2?'已经长大啦 · 还可以继续喂养陪伴':`再喂 ${next-owned.feeds.length} 口，看看新的模样`}</span><progress max="${stage===0?3:6}" value="${stage===0?owned.feeds.length:stage===1?owned.feeds.length-3:6}" aria-label="宠物成长进度"></progress></div><div class="pet-care"><button class="pet-feed" data-action="pet-feed" data-id="${pet.id}" ${p.balance<1?'disabled':''}>喂一口${pet.food}<small>1 ✦</small></button><button class="pet-touch" data-action="pet-touch" aria-label="摸摸${pet.name}">摸摸它 ♡</button></div><p class="pet-hint">今日阅读星星 ${dailyReadingStars(p,today())}/7 · 有时长才奖励</p>`:'<button class="pet-feed" data-action="pet-collection">选一位小伙伴 · 第一只免费</button>'}<div class="pet-links"><button data-action="pet-collection">小伙伴 ${p.owned.length}/5</button><button data-action="pet-growth" ${!owned?'disabled':''}>成长相册</button><button data-action="pet-shop" ${!owned?'disabled':''}>布置小屋</button></div></section>`;
}
export function collectionView(state){const p=petSnapshot(state);return `<p class="pet-sheet-note">${p.owned.length?'每位新伙伴需要 6 颗星星，接回家后随时切换。':'第一只任选，送你 3 颗星星喂它吃饭。'}<br>现在有 <strong>${p.balance} ✦</strong>，伙伴不会因为你忙碌而离开。</p><div class="pet-collection">${PETS.map(pet=>{const owned=p.owned.find(x=>x.id===pet.id),stage=petStage(owned?.feeds.length||0);return `<article>${petPicture(pet.id,stage)}<h3>${pet.name}<small>${pet.kind}</small></h3><p>${owned?pet.stages[stage]:`喜欢吃${pet.food}`}</p><button class="secondary" data-action="pet-adopt" data-id="${pet.id}" ${p.selected===pet.id||(!owned&&p.owned.length&&p.balance<6)?'disabled':''}>${p.selected===pet.id?'正在陪你':owned?'换它来陪我':p.owned.length?'接回家 · 6 ✦':'免费接回家'}</button></article>`;}).join('')}</div>`;}
export function growthView(state,preview=null){const p=petSnapshot(state),owned=p.owned.find(x=>x.id===p.selected);if(!owned)return '';const pet=PETS.find(x=>x.id===p.selected),stage=petStage(owned.feeds.length),show=preview===null?stage:Math.min(stage,preview);return `<div class="growth-preview scene-${p.equipped.scene}">${stageView(pet,show,p)}<h3>${pet.stages[show]}</h3><p>${show===stage?'现在的模样':'小时候的模样 · 只是回看，不会改变成长'}</p></div><div class="growth-stages">${pet.stages.map((name,i)=>`<button data-action="pet-preview" data-stage="${i}" ${i>stage?'disabled':''} aria-pressed="${show===i}">${petPicture(pet.id,i,i>stage?'unrevealed':'')}<strong>${i>stage?'待长大':name}</strong><small>${i===0?'初次见面':`累计喂 ${i===1?3:9} 口`}</small></button>`).join('')}</div><p class="pet-sheet-note">已经一起吃过 ${owned.feeds.length} 餐。每一次照顾，都留在这里。</p>`;}
export function islandCompanion(state,m){const p=petSnapshot(state),owned=p.owned.find(x=>x.id===p.selected);if(!owned||!m.done)return '';const pet=PETS.find(x=>x.id===p.selected),scene=['forest','library'].includes(m.id)?'sky':'garden';p.equipped.scene=scene;return `<section class="growth-preview scene-${scene}">${stageView(pet,petStage(owned.feeds.length),p)}<h3>${pet.name}也来探险啦</h3><p>这段风景，想和你一起看。</p><button class="text-btn" style="margin-top:12px" data-action="pet-touch">摸摸同行的小伙伴 ♡</button></section>`;}
export function shopView(state){const p=petSnapshot(state);return `<p class="pet-sheet-note">小小布置，让这里更像你的家。<strong>${p.balance} ✦</strong><br>已拥有的风景和装饰，可以免费换回来。</p><div class="pet-shop">${PET_ITEMS.map(item=>{const owned=p.items.includes(item.id),equipped=p.equipped[item.type]===item.id;return `<article><div class="item-art item-${item.id}" aria-hidden="true">${{garden:'❀',sky:'☾','heart-rug':'♥','flower-bowl':'✿'}[item.id]}</div><div><h3>${item.name}</h3><p>${item.desc}</p><button class="secondary" data-action="pet-buy" data-id="${item.id}" ${equipped||!owned&&p.balance<item.cost?'disabled':''}>${equipped?'已经摆好':owned?'换上这个':`兑换并摆好 · ${item.cost} ✦`}</button></div></article>`;}).join('')}</div><div class="pet-defaults">${[['scene','回到奶油小屋'],['rug','收起地毯'],['bowl','换回小餐碗']].map(([type,label])=>`<button class="text-btn" data-action="pet-reset" data-type="${type}" ${p.equipped[type]===(type==='scene'?'room':'basic')?'disabled':''}>${label}</button>`).join('')}</div>`;}
export const petRules=`<div class="pet-rules"><p>✦ 第一次接伙伴回家，送你 <b>3 颗星星</b>。</p><p>✦ 每天有时长的<b>第1次阅读得3颗星星</b>，第2、3、4、5次各得1颗，第6次起不再奖励。每天最多7颗，按北京时间的阅读日期重新计算。</p><p>✦ <b>1 颗星星</b>换一份食物并立即喂养。累计喂 3 口、9 口，会长成不同模样。</p><p>✦ 第一只伙伴任选免费，之后每只 <b>6 颗星星</b>。</p><p>不填时长可以保存阅读，但不奖励星星；补填有效时长后再计奖。自动计时需确认保存，手填分钟也可以。只记录分享不奖励。</p><p>同一条已获奖励的阅读，修改分钟或日期都不会重复奖励。删除不收回星星，也不恢复当天已用奖励名额。旧版已发星星保留，算作对应日期的第一档，不重复发3颗。</p><p>忙几天也没关系。小伙伴会一直在这里等你，不会饿坏，也不会离开。</p></div>`;
