// Rebuild the offline thumbnails from the exact interactive 3D models.
const {chromium}=require(process.env.READING_PLAYWRIGHT||'playwright');
const fs=require('node:fs/promises'),http=require('node:http'),path=require('node:path');
const root=path.resolve(__dirname,'..'),mime={'.js':'text/javascript','.png':'image/png'};
const server=http.createServer(async(req,res)=>{try{const file=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',mime[path.extname(file)]||'text/html');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});
(async()=>{await fs.mkdir(path.join(root,'pets'),{recursive:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let browser;
try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:480,height:400},deviceScaleFactor:1});await page.goto(base+'/index.html');
await page.evaluate(()=>{document.head.innerHTML='';document.body.innerHTML='<div id="pet" style="width:480px;height:400px"></div>';document.body.style='margin:0;background:transparent';});
for(const id of ['bunny','cat','dog','monkey','phoenix'])for(const stage of [0,1,2]){await page.evaluate(async({id,stage})=>{window.preview?.dispose();const {createPetStage}=await import('./pet-art.js');window.preview=createPetStage(document.querySelector('#pet'),{id,stage});if(!window.preview)throw Error('WebGL unavailable');},{id,stage});await page.waitForTimeout(80);await page.screenshot({path:path.join(root,'pets',`${id}-${stage}.png`),omitBackground:true});}
await page.evaluate(()=>window.preview?.dispose());await page.setViewportSize({width:1200,height:720});await page.setContent(`<body style="margin:0;display:grid;grid-template-columns:repeat(5,1fr);background:#fff5ef;font-family:system-ui">${[0,1,2].flatMap(stage=>['bunny','cat','dog','monkey','phoenix'].map(id=>`<div style="text-align:center"><img src="${base}/pets/${id}-${stage}.png" style="width:240px;height:210px;object-fit:contain"><div>${id} · ${stage+1}</div></div>`)).join('')}</body>`);await page.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await page.screenshot({path:path.join(root,'tests/pets-contact-sheet.png')});
console.log('Rendered 15 pet portraits and review contact sheet.');}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
